name: Example

on:
  push: 
    branches: [main, master]

jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: disable workflow commands
        run: |
          echo '::warning:: this is a warning'
          echo ${{ secrets.TOKEN }}