# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

# Merges the repo's default branch into a PR when the "merge main" label is added
# Note: you'll need to add a personal access token to your repo, `PERSONAL_ACCESS_TOKEN`.

name: Merge Main into PR - 2022

on:
  pull_request:
    types: [labeled]

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    if: ${{ github.event.label.name == 'merge main' }}
    name: Merge Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: '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'
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: perform merge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git pull
          git checkout "$DEFAULT_BRANCH"
          git status
          git checkout "$GITHUB_HEAD_REF"
          git merge "$DEFAULT_BRANCH" --no-edit
          git push
          git status
      # https://github.com/marketplace/actions/actions-ecosystem-remove-labels
      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: merge main